# -*- coding: utf-8 -*-
"""Project: 5 Hangman Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJvjb9WMdgHeTs44KqcbIenzyL-MCOXo
"""

import random
words = ['python', 'streamlit', 'coding', 'cursor', 'programming']
word = random.choice(words)
guessed_letters = []
attempts = 6

print("Welcome to the game.")
print("_" * len(word))


while attempts > 0:
  guess = input("\n Guess the letters: ").lower()

  if len(guess) != 1 or not guess.isalpha():
    print("Write one alphabet only!")
    continue
  if guess in guessed_letters:
    print("This letter is already guessed, choose another letter.")
    continue

    guessed_letters.append(guess)

  if guess in word:
    print("Correct guess.")
  else:
      attempts -= 1
      print(f"Wrong {attempts} attempt.")


      displayed_word = " ".join([letter if letter in guessed_letters else "_" for letter in word])
      print(displayed_word)


  if "_" not in displayed_word:
     print(f"Congratulation! The correct word is: {word}")
     break

  else:
     print(f"Game over! The correct word is: {word}")